// utils/data.js
export const data = {
  products: [
    {
      id: '1',
      name: 'GUCCI 가디건',
      image: '/images/p1.jpg',
      price: 200,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: '구찌 가디건을 사면 구찌 가방이 덤!',
    },
    {
      id: '2',
      name: 'FENDI 가디건',
      image: '/images/p2.jpg',
      price: 195,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: '고급스러운 느낌의 펜디 가디건!',
    },
    {
      id: '3',
      name: 'LOUIS VUITTON 아우터',
      image: '/images/p3.jpg',
      price: 250,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: '올겨울 걱정없는 루이비통 털 아우터!',
    },
    {
      id: '4',
      name: '곰돌이 가디건',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '귀여운 곰돌이가 그려진 니트 가디건!',
    },
    {
      id: '5',
      name: 'THOM BROWNE Gray 가디건',
      image: '/images/p5.jpg',
      price: 180,
      countInStock: 5,
      rating: 4.5,
      numReviews: 14,
      description: '멋쟁이가 될 수 있는 톰브라운 가디건!',
    },
    {
      id: '6',
      name: 'THOM BROWNE Ivory 가디건',
      image: '/images/p6.jpg',
      price: 180,
      countInStock: 13,
      rating: 4.1,
      numReviews: 12,
      description: '우아한 색상의 톰브라운 가디건!',
    },
    {
      id: '7',
      name: '트위드 자켓',
      image: '/images/p7.jpg',
      price: 200,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: '고급스러운 분위기 연출 가능한 트위드 자켓!',
    },
    {
      id: '8',
      name: '셔츠 & 조끼 Set',
      image: '/images/p8.jpg',
      price: 130,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '초록색 체크 셔츠와 검정 조끼의 조화!',
    },
  ],
}
